In [1]:
import numpy as np
from numba import cuda

In [2]:
@cuda.jit
def matrixMul(A, B, C):
    row, col = cuda.grid(2)
    if row < N and col < K:
        sum_val = 0.0
        for i in range(M):
            sum_val += A[row, i] * B[i, col]
        C[row, col] = sum_val

In [3]:
size = int(input("enter the size of matrix: "))

M = N = K = size

# A = np.random.randn(N, M).astype(np.float32)
A = np.random.randint(2, size=(N, M)).astype(np.float32)
# B = np.random.randn(M, K).astype(np.float32)
B = np.random.randint(2, size=(N, M)).astype(np.float32)
C = np.zeros((N, K), dtype=np.float32)

d_A = cuda.to_device(A)
d_B = cuda.to_device(B)
d_C = cuda.to_device(C)

block_dim = (32, 32)
grid_dim = ((N + block_dim[0] - 1) // block_dim[0], (K + block_dim[1] - 1) // block_dim[1])

matrixMul[grid_dim, block_dim](d_A, d_B, d_C)

C = d_C.copy_to_host()

print(C)

enter the size of matrix: 4


/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:488: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


[[1. 1. 1. 3.]
 [1. 1. 2. 1.]
 [0. 0. 1. 1.]
 [2. 2. 1. 2.]]
